structure(list(url = "https://env-167618.customer.cloud.microstrategy.com/MicroStrategyLibrary/api/auth/login", 
    status_code = 204L, headers = structure(list(date = "Wed, 13 Nov 2019 16:26:39 GMT", 
        `set-cookie` = "REDACTED", `x-mstr-authtoken` = "ek93m4oocifekbaqss6ulstrjj", 
        `cache-control` = "no-cache, no-store, max-age=0, must-revalidate", 
        pragma = "no-cache", expires = "0", server = "MicroStrategy"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 204L, version = "HTTP/2", 
        headers = structure(list(date = "Wed, 13 Nov 2019 16:26:39 GMT", 
            `set-cookie` = "REDACTED", `x-mstr-authtoken` = "ek93m4oocifekbaqss6ulstrjj", 
            `cache-control` = "no-cache, no-store, max-age=0, must-revalidate", 
            pragma = "no-cache", expires = "0", server = "MicroStrategy"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = c("#HttpOnly_env-167618.customer.cloud.microstrategy.com", 
    "env-167618.customer.cloud.microstrategy.com"), flag = c(FALSE, 
    FALSE), path = c("/MicroStrategyLibrary", "/MicroStrategyLibrary"
    ), secure = c(TRUE, FALSE), expiration = structure(c(Inf, 
    Inf), class = c("POSIXct", "POSIXt")), name = c("JSESSIONID", 
    "iSession"), value = c("REDACTED", "REDACTED")), row.names = c(NA, 
    -2L), class = "data.frame"), content = raw(0), date = structure(1573662399, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = c(redirect = 0, namelookup = 2.6e-05, 
    connect = 2.7e-05, pretransfer = 9.4e-05, starttransfer = 1e-04, 
    total = 0.263658)), class = "response")
