structure(list(url = "https://env-167618.customer.cloud.microstrategy.com/MicroStrategyLibrary/api/reports/1B139A5411EA056500000080EFB5E261/instances?offset=0&limit=25000", 
    status_code = 200L, headers = structure(list(date = "Tue, 12 Nov 2019 16:14:52 GMT", 
        `content-type` = "application/json", `content-length` = "948", 
        connection = "keep-alive", `cache-control` = "no-store", 
        `x-content-type-options` = "nosniff", `access-control-allow-methods` = "GET, POST, DELETE, PUT, PATCH, HEAD, OPTIONS", 
        `x-xss-protection` = "1; mode=block", `access-control-allow-headers` = "Content-Type", 
        `content-encoding` = "gzip", server = "MicroStrategy"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 12 Nov 2019 16:14:52 GMT", 
            `content-type` = "application/json", `content-length` = "948", 
            connection = "keep-alive", `cache-control` = "no-store", 
            `x-content-type-options` = "nosniff", `access-control-allow-methods` = "GET, POST, DELETE, PUT, PATCH, HEAD, OPTIONS", 
            `x-xss-protection` = "1; mode=block", `access-control-allow-headers` = "Content-Type", 
            `content-encoding` = "gzip", server = "MicroStrategy"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = c("#HttpOnly_env-167618.customer.cloud.microstrategy.com", 
    "env-167618.customer.cloud.microstrategy.com"), flag = c(FALSE, 
    FALSE), path = c("/MicroStrategyLibrary", "/MicroStrategyLibrary"
    ), secure = c(TRUE, FALSE), expiration = structure(c(Inf, 
    Inf), class = c("POSIXct", "POSIXt")), name = c("JSESSIONID", 
    "iSession"), value = c("REDACTED", "REDACTED")), row.names = c(NA, 
    -2L), class = "data.frame"), content = charToRaw("{\"id\":\"1B139A5411EA056500000080EFB5E261\",\"name\":\"API_RESPONSE_DATA_REPORT\",\"status\":1,\"instanceId\":\"0992F88E11EA0631C0D60080EFD54317\",\"source\":{\"name\":\"API_RESPONSE_DATA\",\"id\":\"F29FCC3211EA056400000080EF55215F\"},\"result\":{\"definition\":{\"metrics\":[{\"name\":\"Pclass\",\"id\":\"EBF9617211EA05641CA90080EFE54362\",\"type\":\"Metric\",\"min\":11.0,\"max\":11.0,\"dataType\":\"Double\",\"numberFormatting\":{\"category\":9,\"formatString\":\"General\"}},{\"name\":\"Survived\",\"id\":\"EBF978D811EA05641CA90080EFE54362\",\"type\":\"Metric\",\"min\":2.0,\"max\":2.0,\"dataType\":\"Double\",\"numberFormatting\":{\"category\":9,\"formatString\":\"General\"}}],\"attributes\":[{\"name\":\"PassengerId\",\"id\":\"EBB2160A11EA056427640080EFB5E261\",\"type\":\"Attribute\",\"forms\":[{\"id\":\"45C11FA478E745FEA08D781CEA190FE5\",\"name\":\"ID\",\"dataType\":\"Real\",\"baseFormCategory\":\"ID\",\"baseFormType\":\"Number\"}]}],\"thresholds\":[],\"sorting\":[]},\"data\":{\"paging\":{\"total\":2,\"current\":1,\"offset\":0,\"limit\":1,\"prev\":null,\"next\":null},\"root\":{\"isPartial\":true,\"children\":[{\"depth\":0,\"element\":{\"attributeIndex\":0,\"formValues\":{\"ID\":\"115\"},\"name\":\"115\",\"id\":\"h115;EBB2160A11EA056427640080EFB5E261\"},\"metrics\":{\"Pclass\":{\"rv\":11.0,\"fv\":\"11\",\"mi\":0},\"Survived\":{\"rv\":2.0,\"fv\":\"2\",\"mi\":1}}}]}}}}"), 
    date = structure(1573575292, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.6e-05, 
    connect = 4.7e-05, pretransfer = 0.000155, starttransfer = 0, 
    total = 0.193405)), class = "response")
