structure(list(url = "https://env-167618.customer.cloud.microstrategy.com/MicroStrategyLibrary/api/cubes/?id=F29FCC3211EA056400000080EF55215F", 
    status_code = 200L, headers = structure(list(date = "Wed, 13 Nov 2019 15:14:57 GMT", 
        `content-type` = "application/json", `content-length` = "260", 
        `cache-control` = "no-store", `x-content-type-options` = "nosniff", 
        `access-control-allow-methods` = "GET, POST, DELETE, PUT, PATCH, HEAD, OPTIONS", 
        `x-xss-protection` = "1; mode=block", `access-control-allow-headers` = "Content-Type", 
        `content-encoding` = "gzip", server = "MicroStrategy"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(date = "Wed, 13 Nov 2019 15:14:57 GMT", 
            `content-type` = "application/json", `content-length` = "260", 
            `cache-control` = "no-store", `x-content-type-options` = "nosniff", 
            `access-control-allow-methods` = "GET, POST, DELETE, PUT, PATCH, HEAD, OPTIONS", 
            `x-xss-protection` = "1; mode=block", `access-control-allow-headers` = "Content-Type", 
            `content-encoding` = "gzip", server = "MicroStrategy"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = c("#HttpOnly_env-167618.customer.cloud.microstrategy.com", 
    "env-167618.customer.cloud.microstrategy.com"), flag = c(FALSE, 
    FALSE), path = c("/MicroStrategyLibrary", "/MicroStrategyLibrary"
    ), secure = c(TRUE, FALSE), expiration = structure(c(Inf, 
    Inf), class = c("POSIXct", "POSIXt")), name = c("JSESSIONID", 
    "iSession"), value = c("REDACTED", "REDACTED")), row.names = c(NA, 
    -2L), class = "data.frame"), content = charToRaw("{\"cubesInfos\":[{\"cubeName\":\"API_RESPONSE_DATA\",\"cubeId\":\"F29FCC3211EA056400000080EF55215F\",\"ownerId\":\"7FC05A65473CE2FD845CE6A1D3F13233\",\"path\":\"\\\\MicroStrategy Tutorial\\\\Profiles\\\\MSTR User (mstr)\\\\My Reports\\\\API_RESPONSE_DATA\",\"modificationTime\":\"2019-11-12 15:56:11\",\"serverMode\":1,\"size\":852992,\"status\":17518}]}"), 
    date = structure(1573658097, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 6.1e-05, 
    connect = 6.5e-05, pretransfer = 0.000176, starttransfer = 0.172578, 
    total = 0.172724)), class = "response")
