structure(list(url = "https://env-167618.customer.cloud.microstrategy.com/MicroStrategyLibrary/api/cubes/?id=DB80F84011E9F65B00000080EF854BEA", 
    status_code = 200L, headers = structure(list(date = "Tue, 12 Nov 2019 11:16:26 GMT", 
        `content-type` = "application/json", `content-length` = "250", 
        `cache-control` = "no-store", `x-content-type-options` = "nosniff", 
        `access-control-allow-methods` = "GET, POST, DELETE, PUT, PATCH, HEAD, OPTIONS", 
        `x-xss-protection` = "1; mode=block", `access-control-allow-headers` = "Content-Type", 
        `content-encoding` = "gzip", server = "MicroStrategy"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(date = "Tue, 12 Nov 2019 11:16:26 GMT", 
            `content-type` = "application/json", `content-length` = "250", 
            `cache-control` = "no-store", `x-content-type-options` = "nosniff", 
            `access-control-allow-methods` = "GET, POST, DELETE, PUT, PATCH, HEAD, OPTIONS", 
            `x-xss-protection` = "1; mode=block", `access-control-allow-headers` = "Content-Type", 
            `content-encoding` = "gzip", server = "MicroStrategy"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = c("#HttpOnly_env-167618.customer.cloud.microstrategy.com", 
    "env-167618.customer.cloud.microstrategy.com"), flag = c(FALSE, 
    FALSE), path = c("/MicroStrategyLibrary", "/MicroStrategyLibrary"
    ), secure = c(TRUE, FALSE), expiration = structure(c(Inf, 
    Inf), class = c("POSIXct", "POSIXt")), name = c("JSESSIONID", 
    "iSession"), value = c("REDACTED", "REDACTED")), row.names = c(NA, 
    -2L), class = "data.frame"), content = charToRaw("{\"cubesInfos\":[{\"cubeName\":\"iris1\",\"cubeId\":\"DB80F84011E9F65B00000080EF854BEA\",\"ownerId\":\"7FC05A65473CE2FD845CE6A1D3F13233\",\"path\":\"\\\\MicroStrategy Tutorial\\\\Profiles\\\\MSTR User (mstr)\\\\My Reports\\\\iris1\",\"modificationTime\":\"2019-10-25 15:13:10\",\"serverMode\":1,\"size\":361472,\"status\":17518}]}"), 
    date = structure(1573557386, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.4e-05, 
    connect = 4.7e-05, pretransfer = 0.000149, starttransfer = 0.155771, 
    total = 0.155889)), class = "response")
