structure(list(url = "https://env-167618.customer.cloud.microstrategy.com/MicroStrategyLibrary/api/status", 
    status_code = 200L, headers = structure(list(date = "Wed, 13 Nov 2019 16:26:39 GMT", 
        `content-type` = "application/json", `content-length` = "203", 
        `cache-control` = "no-store", `x-content-type-options` = "nosniff", 
        `access-control-allow-methods` = "GET, POST, DELETE, PUT, PATCH, HEAD, OPTIONS", 
        `x-xss-protection` = "1; mode=block", `access-control-allow-headers` = "Content-Type", 
        `content-encoding` = "gzip", server = "MicroStrategy"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(date = "Wed, 13 Nov 2019 16:26:39 GMT", 
            `content-type` = "application/json", `content-length` = "203", 
            `cache-control` = "no-store", `x-content-type-options` = "nosniff", 
            `access-control-allow-methods` = "GET, POST, DELETE, PUT, PATCH, HEAD, OPTIONS", 
            `x-xss-protection` = "1; mode=block", `access-control-allow-headers` = "Content-Type", 
            `content-encoding` = "gzip", server = "MicroStrategy"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = c("#HttpOnly_env-167618.customer.cloud.microstrategy.com", 
    "env-167618.customer.cloud.microstrategy.com"), flag = c(FALSE, 
    FALSE), path = c("/MicroStrategyLibrary", "/MicroStrategyLibrary"
    ), secure = c(TRUE, FALSE), expiration = structure(c(Inf, 
    Inf), class = c("POSIXct", "POSIXt")), name = c("JSESSIONID", 
    "iSession"), value = c("REDACTED", "REDACTED")), row.names = c(NA, 
    -2L), class = "data.frame"), content = charToRaw("{\"upSince\":1573625148864,\"upTime\":37250313,\"upTimeText\":\"10 Hours 20 Minutes 50 seconds\",\"webVersion\":\"11.1.0400.23840J\",\"baseUri\":\"https://env-167618.customer.cloud.microstrategy.com/MicroStrategyLibrary/api/\",\"iServerVersion\":\"11.1.0400.26937\"}"), 
    date = structure(1573662399, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 6.7e-05, 
    connect = 7.1e-05, pretransfer = 0.000183, starttransfer = 0.109974, 
    total = 0.110082)), class = "response")
